version: '3.8'

services:
  db: 
    image: 'postgres:9.5'
    volumes: 
        - postgres:/var/lib/postgresql/data
    environment:
        - POSTGRES_USERNAME=postgres
        - POSTGRES_PASSWORD=postgres

  app:
    depends_on: 
        - db
    build: .
    command: bash start.sh
    ports: 
        - '9292:9292'
    environment: 
        - DB_PASSWORD=postgres
        - LANG=C.UTF-8
    volumes: 
        - .:/onebitbot
        - gems:/gems

volumes:
  postgres:
  gems: